apiVersion: apps/v1
kind: Deployment
metadata:
  name: toystore-app
  labels:
    app: toystore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: toystore
  template:
    metadata:
      labels:
        app: toystore
    spec:
      containers:
      - name: toystore-container
        image: toystoreappimage:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"


---
apiVersion: v1
kind: Service
metadata:
  name: toystore-service
  labels:
    app: toystore
spec:
  selector:
    app: toystore
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  