apiVersion: apps/v1
kind: Deployment
metadata:
  name: toystoreapp
  namespace: toystore
spec:
  replicas: 4
  selector:
    matchLabels:
      app: toystoreapp
  template:
    metadata:
      labels:
        app: toystoreapp
    spec:
      containers:
      - name: toystoreapp
        image: kavitharc.azurecr.io/toystoreapp:latest
        ports:
        - containerPort: 8000