apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: toystoreapp-ingress
  namespace: toystore
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: toystore.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: toystoreapp-service
            port:
              number: 8000  