apiVersion: v1
kind: Service
metadata:
  name: toystoreapp-service
  namespace: toystore
spec:
  selector:
    app: toystoreapp
  ports:
  - name: http
    port: 8000        # Service port
    targetPort: 8000  # Container port
    protocol: TCP
  type: ClusterIP